import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "ESTI Personality Test",
  description: "Generated by create next app",
  icons : {
    icon : './favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className='headerdiv' id='top'>
            <h1>
              ESTI Personality Test
            </h1>
            <h2> a reimplementation of the MBTI personality test using the Mamdani fuzzy inference engine</h2>
        </div>
        {children}
      </body>
    </html>
  );
}
